/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Logica.ParPalabra;
import Persistencia.Diccionario;
import java.awt.Dialog;
import java.text.Normalizer.Form;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Configuracion extends javax.swing.JDialog {
    //Atributos
    protected Diccionario newDict = new Diccionario();
    protected ParPalabra pp = new ParPalabra();
    
    /** Creates new form Configuracion */
    public Configuracion() {
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        mostrarDatosTabla("");
        reiniciarEspacioInputs();
        actualizarEstadoBotones();
    }
    
    //Metodos
    public void reiniciarEspacioInputs(){
        this.jID.setText("");
        this.jEspanol.setText("");
        this.jIngles.setText((""));
        this.jCategoria.setText("");
        this.jImagen.setText("");
    }
    
    private void mostrarDatosTabla(String sqlSent){
        List<ParPalabra> listaDePalabras = this.newDict.DictListaDePalabras(sqlSent);
        Object[][] datosFila = new Object[1][5];
        Object[] datosColumnas = {"ID", "Espanol", "Ingles", "Categoria", "Imagen"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(datosColumnas);
        this.jDictTable.setModel(model);
        
        for(ParPalabra item: listaDePalabras){
            datosFila[0][0] = item.getID();
            datosFila[0][1] = item.getEspanol();
            datosFila[0][2] = item.getIngles();
            datosFila[0][3] = item.getCategoria();
            datosFila[0][4] = item.getImagen();
            model.addRow(datosFila[0]);
        }
    }   
    
    public void actualizarEstadoBotones(){
        boolean vacioID = this.jID.getText().isEmpty();
        boolean vacioEspanol = this.jEspanol.getText().isEmpty();
        boolean vacioIngles = this.jIngles.getText().isEmpty();
        
        // Condicion para boton Agregar Palabra
        if(vacioEspanol || vacioIngles){
            this.jAgregar.setEnabled(false);
        }
        else{
            this.jAgregar.setEnabled(true);
        }
        
        // Condicion para botones Actualizar y Eliminar Palabra
        if(vacioEspanol || vacioIngles || vacioID){
            this.jActualizar.setEnabled(false);
            this.jEliminar.setEnabled(false);
        }
        else{
            this.jActualizar.setEnabled(true);
            this.jEliminar.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jEspanol = new javax.swing.JTextField();
        jCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jImagen = new javax.swing.JTextField();
        jIngles = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDictTable = new javax.swing.JTable();
        jEliminar = new javax.swing.JButton();
        jAgregar = new javax.swing.JButton();
        jConsultar = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DuoLingoFV");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Espanol");

        jEspanol.setText("\"Palabra\"");
        jEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEspanolActionPerformed(evt);
            }
        });
        jEspanol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEspanolKeyReleased(evt);
            }
        });

        jCategoria.setText("\"Palabra\"");
        jCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Categoria");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Imagen");

        jImagen.setText("Path");
        jImagen.setMinimumSize(new java.awt.Dimension(59, 22));
        jImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImagenActionPerformed(evt);
            }
        });

        jIngles.setText("\"Palabra\"");
        jIngles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jInglesKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Ingles");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Datos de la Palabra:");

        jID.setText("\"Palabra\"");
        jID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDActionPerformed(evt);
            }
        });
        jID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEspanol, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jID, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jIngles))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEspanol)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jID, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Configuracion del diccionario");

        jDictTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDictTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDictTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jDictTable);

        jEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jAgregar.setText("Agregar");
        jAgregar.setPreferredSize(new java.awt.Dimension(89, 22));
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jConsultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jConsultar.setText("Consultar");
        jConsultar.setPreferredSize(new java.awt.Dimension(89, 22));
        jConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarActionPerformed(evt);
            }
        });

        jActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jActualizar.setText("Actualizar");
        jActualizar.setPreferredSize(new java.awt.Dimension(89, 22));
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEspanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEspanolActionPerformed

    private void jCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCategoriaActionPerformed

    private void jImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jImagenActionPerformed
    
    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // Get the information from the menu and Create a new word
        String sqlSent;
        try{
            if(jID.getText().length()==0 && (jEspanol.getText().length()!=0) && jIngles.getText().length()!=0){
                this.pp.setEspanol(jEspanol.getText());
                this.pp.setIngles(jIngles.getText());
                this.pp.setCategoria(jCategoria.getText());
                this.pp.setImagen(jImagen.getText());
                sqlSent = "INSERT INTO ListaDePalabras(Espanol, Ingles, Categoria, Imagen)" 
                        + " VALUES('" + this.pp.getEspanol() + "', '" + this.pp.getIngles() + "', '" + this.pp.getCategoria() + "', '" 
                        + this.pp.getImagen() + "');"; 
                this.newDict.agregarPalabra(sqlSent);
                mostrarDatosTabla("");
                reiniciarEspacioInputs();
            }
            else{
                this.pp.setID(Integer.parseInt(jID.getText()));
                this.pp.setEspanol(jEspanol.getText());
                this.pp.setIngles(jIngles.getText());
                this.pp.setCategoria(jCategoria.getText());
                this.pp.setImagen(jImagen.getText());
                sqlSent = "INSERT INTO ListaDePalabras(ID, Espanol, Ingles, Categoria, Imagen)"
                        + " VALUES('" + this.pp.getID() + "', '" + this.pp.getEspanol() + "', '" + this.pp.getIngles() 
                        + "', '" + this.pp.getCategoria()+ "', '" + this.pp.getImagen() + "');";          
                this.newDict.agregarPalabra(sqlSent);
                mostrarDatosTabla("");
                reiniciarEspacioInputs();
            }
        }
        catch(NumberFormatException ex){
            System.out.println("Error: Todos los campos estan vacios (" + ex + ")");
        }
        actualizarEstadoBotones();
    }//GEN-LAST:event_jAgregarActionPerformed
 
    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        String sqlSentence;
        try{
            this.pp.setID(Integer.parseInt(jID.getText()));
            sqlSentence = "DELETE FROM ListaDePalabras WHERE " + "ID='" + this.pp.getID() + "';";
            this.newDict.eliminarPalabra(sqlSentence);
            mostrarDatosTabla("");
            reiniciarEspacioInputs();
        }
        catch(NumberFormatException ex){
            System.out.println("Error: Debe ingresar un ID (" + ex + ")");
        }
        actualizarEstadoBotones();
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDActionPerformed
        // TODO add your handling code here:
        actualizarEstadoBotones();
    }//GEN-LAST:event_jIDActionPerformed

    private void jConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarActionPerformed
        // TODO add your handling code here:
        String sqlSent;
        try{
            if(this.jID.getText().isEmpty()){
                this.pp.setID(-1);
            }
            else{
                this.pp.setID(Integer.parseInt(this.jID.getText()));
            }
            this.pp.setEspanol(jEspanol.getText());
            this.pp.setIngles(jIngles.getText());
            this.pp.setCategoria(jCategoria.getText());
            this.pp.setImagen(jImagen.getText());

            if(this.pp.getID() == -1 && this.pp.getEspanol() == "NoEspanol" && this.pp.getIngles() == "NoIngles" 
                    && this.pp.getCategoria() == "NoCategoria" && this.pp.getImagen() == "NoImage"){
                System.out.println("Estamos aca");
                sqlSent = "";
            }
            else{
                sqlSent = " WHERE ID='" + this.pp.getID() + "' OR Espanol='" + this.pp.getEspanol() 
                    + "' OR Ingles='" + this.pp.getIngles() + "' OR Categoria='" + this.pp.getCategoria() + "';";              
            }
            mostrarDatosTabla(sqlSent);
            reiniciarEspacioInputs();
        }
        catch(NumberFormatException ex){
            System.out.println("Error: Input de ID invalido (" + ex + ")");
        }
        actualizarEstadoBotones();
    }//GEN-LAST:event_jConsultarActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
        String sqlSent;
        try{
            this.pp.setID(Integer.parseInt(jID.getText()));
            this.pp.setEspanol(jEspanol.getText());
            this.pp.setIngles(jIngles.getText());
            this.pp.setCategoria(jCategoria.getText());
            this.pp.setImagen(jImagen.getText());
            sqlSent = "UPDATE ListaDePalabras" 
                    + " SET Espanol='" + this.pp.getEspanol() + "', Ingles='" + this.pp.getIngles() 
                    + "', Categoria='" + this.pp.getCategoria() + "', Imagen='" + this.pp.getImagen() 
                    + "' WHERE ID='" + this.pp.getID() + "';";
            
            this.newDict.actualizarPalabra(sqlSent);
            mostrarDatosTabla("");
            reiniciarEspacioInputs();
        }
        catch(NumberFormatException ex){
            System.out.println("Error: Debe ingresar un ID (" + ex + ")");
        }
        actualizarEstadoBotones();
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jEspanolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEspanolKeyReleased
        // TODO add your handling code here:
        this.actualizarEstadoBotones();
    }//GEN-LAST:event_jEspanolKeyReleased

    private void jInglesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jInglesKeyReleased
        // TODO add your handling code here:
        this.actualizarEstadoBotones();
    }//GEN-LAST:event_jInglesKeyReleased

    private void jIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIDKeyReleased
        // TODO add your handling code here:
        this.actualizarEstadoBotones();
    }//GEN-LAST:event_jIDKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jAgregar;
    private javax.swing.JTextField jCategoria;
    private javax.swing.JButton jConsultar;
    private javax.swing.JTable jDictTable;
    private javax.swing.JButton jEliminar;
    private javax.swing.JTextField jEspanol;
    private javax.swing.JTextField jID;
    private javax.swing.JTextField jImagen;
    private javax.swing.JTextField jIngles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
